task runGradleTest

allprojects {
	repositories {
		maven {
			url file("repo")
		}
	}
}

runGradleTest {
	dependsOn upgradeJakarta

	doLast {
		File file = new File(buildDir.getParentFile(), "modules/foo-web/build.gradle")

		assert file.text.contains('version: "9.9.9"')
		assert !file.text.contains('javax.portlet')
	}
}